services:
  db-messenger:
    container_name: db-messenger
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER:-localhost}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-messenger}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - app-network

  backend-messenger:
    build:
      context: ../backend
    container_name: backend-messenger
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER:-db-messenger}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-messenger}
    volumes:
      - ../backend:/app
    ports:
      - "8001:8000"
    depends_on:
      - db-messenger
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_volume: