services:
  db-messenger:
    container_name: db-messenger
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER:-localhost}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-messenger}
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - db_messenger_volume:/var/lib/postgresql/data
    networks:
      - app-network

  db-auth:
    container_name: db-auth
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_SERVER: ${POSTGRES_AUTH_SERVER:-localhost}
      POSTGRES_USER: ${POSTGRES_AUTH_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_AUTH_DB:-auth}
    ports:
      - "5433:${POSTGRES_AUTH_PORT}"
    volumes:
      - db_auth_volume:/var/lib/postgresql/data
    networks:
      - app-network

  backend-messenger:
    build:
      context: ../backend/messenger
    container_name: backend-messenger
    environment:
      POSTGRES_SERVER: ${POSTGRES_SERVER:-db-messenger}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_MESSENGER_DB: ${POSTGRES_MESSENGER_DB:-messenger}
      SECRET_KEY: ${SECRET_KEY:-your_secret_key}
    volumes:
      - ../backend/messenger:/app
    ports:
      - "8001:8000"
    depends_on:
      - db-messenger
    networks:
      - app-network

  backend-auth:
    build:
      context: ../backend/auth
    container_name: backend-auth
    environment:
      POSTGRES_SERVER: ${POSTGRES_AUTH_SERVER:-db-auth}
      POSTGRES_USER: ${POSTGRES_AUTH_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_AUTH_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_AUTH_DB:-auth}
      SECRET_KEY: ${SECRET_KEY:-your_secret_key}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-15}
      REFRESH_TOKEN_EXPIRE_DAYS: ${REFRESH_TOKEN_EXPIRE_DAYS:-365}
    volumes:
      - ../backend/auth:/app
    ports:
      - "8002:8000"
    depends_on:
      - db-auth
    networks:
      - app-network

  front-messenger:
    build:
      context: ../front/apps/messenger
    container_name: front-messenger
    ports:
      - "3001:3000"
    networks:
      - app-network

  front-auth:
    build:
      context: ../front
      dockerfile: apps/auth/Dockerfile
    container_name: front-auth
    ports:
      - "3002:3000"
    networks:
      - app-network
  
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - front-messenger
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_auth_volume:
  db_messenger_volume: