version: '3'
services:
  db:
    image: postgres:15.2-alpine
    restart: always
    environment:
      POSTGRES_SERVER=${POSTGRES_SERVER:-localhost}
      POSTGRES_USER=${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      POSTGRES_DB=${POSTGRES_DB:-postgres}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data

volumes:
  db_volume: